### ISSUE TITLE
order or non printing characters with f-string.

### ISSUE THREAD

**Issue by jazzphreak** [MicrosoftDocs/intellicode#109]
Issue Type: <b>Feature Request</b>

Minor issue, but VS Intellicode doesn't flag the following as an error:

print("\t\nWe're glad you could join us!")

The correct syntax is of course print("\n\tWe're glad you could join us!") with the newline character preceding the tab character. This is no way highlighted as error and the Python interperter does print it to the stdio with the new line character. 

Extension version: 1.1.7
VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.18362

**Comment by markw-t** [comment]
hI @jazzphreak , and thanks for taking the time to raise this.

It looks like this is a problem with the Python Language Server rather than with IntellICode's starred recommendations - please could you raise the issue in their issues repo at https://github.com/Microsoft/python-language-server/issues ?

Thanks
Mark

**Comment by jazzphreak** [comment]
Gladly I'll post it there and that makes sense since I tried the same
operation in the sublime text 3 editor and it had the exact same problem.

**Comment by markw-t** [comment]
Thanks @jazzphreak !

**Comment by jazzphreak** [comment]
For traceability, noted original issues (feature request) entered here as issue #109 and logged as #1283 in their docsite.
