### ISSUE TITLE
Couldn't download IntelliCode model. Please check your network connectivity or firewall settings.

### ISSUE THREAD

**Issue by prosenboim** [MicrosoftDocs/intellicode#119]
Acquiring model 'intellisense-members' for python
Querying IntelliCode service for available models.
Couldn't reach service Error Message: connect ECONNREFUSED 127.0.0.1:9000, (Error)
Could not reach the IntelliCode service. Checking the local model cache.
None of the cached models match.
Couldn't download IntelliCode model. Please check your network connectivity or firewall settings. Error Message: connect ECONNREFUSED 127.0.0.1:9000, (Error)
No model available for Python, cannot continue.

I'm running VS Code insiders (Version: 1.38.0-insider) with remote extensions. My main machine is Mac, remote machine runs ubuntu 18. Intellicode version is 1.1.9

The issue looks similar to other issues with downloading behind proxy, except... I'm not behind proxy.

**Comment by osobeso** [comment]
Hi @prosenboim thanks a lot for your feedback.
You're right, this sounds a lot like a Proxy issue.
In order to check if your current configuration is correct, could you please provide us with some more information about your environment configuration (i.e environment variable dump) and also proxy settings on VS code, so we make sure it's not proxy related and it's actually a bug.

Thanks again and let me know if you have any questions.

**Comment by prosenboim** [comment]
[myenv.txt](https://github.com/MicrosoftDocs/intellicode/files/3519210/myenv.txt)
[remoteenv.txt](https://github.com/MicrosoftDocs/intellicode/files/3519211/remoteenv.txt)
![Screen Shot 2019-08-20 at 10 30 56](https://user-images.githubusercontent.com/36269097/63326907-d7a35780-c335-11e9-97ba-cdc1641f1fee.png)


myenv.txt - environment on my MAC
remoteenv.txt - environment on remote machine
Also, attached a screenshot of proxy setting in VScode

**Comment by osobeso** [comment]
Hi @prosenboim 
Thanks a lot for the information provided.
Now that we can put aside the proxy settings, I would like to know a little more information about what steps need to be followed to replicate your current scenario.
You mention you're running remote extensions, but I'm not sure if that has to do with the issue.
I assume the VS code that is displaying the error message you provided is the one that's running locally on your Mac.

Where did you see this error, or what did you do before stumbling upon this error message?
Is it only happening for python? 

I would like to recreate your scenario to test with different languages and check if this problem is only python related and also have more insight on what could be causing this issue.
I also want to check against VS Code Insiders and VS Code, to see if this is only an Insiders problem.

Again, thanks a lot for the feedback and patience, and let me know if you have any questions.

**Comment by prosenboim** [comment]
Hi,
First, it looks like remote extensions are part of the problem. I do not work locally on my Mac, but today I downloaded our code repo locally and opened it in VS code. After opening a python file, I seen a message in status bar about downloading model (don't remember exact message, it was quite quick). It didn't produce any errors. When working on remote machine, I still see same error.

Error appears whenever I open a python file after opening project or VS code window reload.
I never seen this message when opening a C file. (Project I'm working on is mostly C and Python).

**Comment by prosenboim** [comment]
Ok, today I kept playing around - it looks like problem caused by weird internet security program, recently installed by our IT. When I turn it off, problem completely disappears. Sorry for bothering you.

**Comment by osobeso** [comment]
@prosenboim Glad that you found a way to fix the problem. 
Happy coding!
