### ISSUE TITLE
Java Intellisense/autocomplete slow/not working

### ISSUE THREAD

**Issue by imankur85** [MicrosoftDocs/intellicode#127]
Issue Type: <b>Bug</b>

After a brief period of working, the Java intellisense either stops working or takes a lot of time to load suggestions.

Extension version: 1.1.9
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (5.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Eskibear** [comment]
You can open an issue in [redhat-developer/vscode-java](https://github.com/redhat-developer/vscode-java) with the server log attached, for them to look for the root cause.

And there is [a similar issue](https://github.com/redhat-developer/vscode-java/issues/428#issuecomment-362293920) and below is the workaround, FYI
> You can clean the workspace directory in the following way:
Open the command palette (F1)
select Java: Clean the Java language server workspace
click Restart and delete

**Comment by howardchengvmg** [comment]
I am working on a project with thousands of Java classes and at first Intellisense for Java is show and sometimes it looks like it is hanged. However, I tweaked the java.jdt.ls.vmargs settings to increase the initial heap size to 1G and the speed greatly improve.

**Comment by markw-t** [comment]
Hi @imankur85 - as @Eskibear noted above this is a VS Code Java problem that you should report at https://github.com/redhat-developer/vscode-java - since it's not an IntelliCode issue I'll close out this report.

Thanks for trying [IntelliCode](https://aka.ms/vsic/xtn/vscode) - if you do hit any issues with it or want to pass along feedback about it, don't hesitate to open a new issue!

Regards
Mark
