### ISSUE TITLE
Change entry point to train models in VS

### ISSUE THREAD

**Issue by timheuer** [MicrosoftDocs/intellicode#143]
While using the steps outlined https://docs.microsoft.com/en-us/visualstudio/intellicode/custom-models#repository-associated-team-models the entry point to the commands to associate/list/delete models is through View...Other Windows menu options.  

These commands do not result in Other Windows, nor do we actually view anything.  The commands should be moved somewhere else and retain taxonomy of what Other Windows means in Visual Studio

**Comment by catycaldwell** [comment]
Thanks for the feedback, @timheuer. We are optimizing for relatively cheap user experience since we don't anticipate many people needing to train their models often (i.e. most users will automatically acquire the model via their team's repo). Would it be more useful for us to automatically open the Output for you to track the IntelliCode training progress OR would you prefer for us to create another UI (i.e. retain the taxonomy of what Other Windows means in VS) specifically for displaying IntelliCode training commands/output?

**Comment by catycaldwell** [comment]
@timheuer - my bad. This was a response to issue 144. Thanks for sharing this feedback.

**Comment by timheuer** [comment]
Perhaps this could be just similar to #144 as I note there that I believe you already have an appropriate entry point for these three commands.

**Comment by markw-t** [comment]
Reopening due to erroneous bot closure. Apologies for any confusion

**Comment by ayim** [comment]
We've actually released an update that removes the need to train models in order to rank custom classes. Full details here:
https://devblogs.microsoft.com/visualstudio/upgrading-from-intellicode-custom-team-completions-models-to-deep-learning/
