### ISSUE TITLE
Typescript intellisense is causing memory issues

### ISSUE THREAD

**Issue by ChrisLebbano** [MicrosoftDocs/intellicode#159]
My memory usage in one of the processes by the visual studio application spikes to 12 gigs when intellisense is triggered.

**Comment by markw-t** [comment]
Chris, thanks a lot for taking the time to report this issue.

We would like to confirm that the problem you are seeing is related to IntelliCode (rather than a generic issue with TypeScript IntelliSense in Visual Studio). 

To confirm this please can you try doing the same things that appeared to generate the memory spike with the IntelliCode extension disabled or uninstalled, check the memory situation,  then reactivate IntelliCode, restart VS and repeat? If the problem appears to go away with IntelliCode disabled and returns when it is reenabled, we will investigate as a likely IntelliCode problem; if not the TypeScript tools team would like to take a look. 

It would also help if you can file a report using Help -> Report A Problem (and capture your Repro Steps) in Visual Studio and let us know the report identity which the tool will give you (a URL on the Developer Community site). 

tagging @minestarks @uniqueiniquity

**Comment by ChrisLebbano** [comment]
I'm going to close this.  I was confused as to why the Visual Studio report a problem directed me here.  I am not currently using this extension.

**Comment by markw-t** [comment]
thanks @ChrisLebbano . The IntelliCode extension is installed by default in more recent builds of Visual Studio, so it's entirely possible that you have it enabled without realizing it - if you see "stars" at the top of your IntelliSense lists for TypeScript recommending particular methods/properties when using Visual Studio, you have IntelliCode (you can also check in the extensions manager, which is where you can disable it).

**Comment by ChrisLebbano** [comment]
Thanks, so I was unaware this was installed because I didn't remember this one.
I did disable it and I will keep an eye on the memory spiking.

**Comment by markw-t** [comment]
Thank you @ChrisLebbano  - I appreciate that. I'd love to hear any feedback you may have about the feature (separate to this bug), so please do drop me a line once you've had a chance to notice it more (https://aka.ms/intellicode has more info, just click on the TypeScript tab).

**Comment by ChrisLebbano** [comment]
Disabling this extension and restarting VSCode did not fix the issue.  I will keep this closed.

![image](https://user-images.githubusercontent.com/18106682/71740977-ab433000-2e2b-11ea-967a-ff4898bf8995.png)

**Comment by markw-t** [comment]
Thanks for this Chris. Adding @Benjamin Lichtman<mailto:Benjamin.Lichtman@microsoft.com> and @Mine Starks<mailto:Mine.Yalcinalp@microsoft.com>

I had thought that you had Visual Studio (rather than Visual Studio Code) from your original report. I’ll let Ben and Mine guide you on next steps for reporting and followup.

Thanks
Mark

**Comment by ChrisLebbano** [comment]
My mistake sorry I assumed this was an area for visual stuido code only so I assumed omitting the 'code' part was alright.

**Comment by markw-t** [comment]
No problem - and again thanks for the report. This is indeed our reporting location for VS Code IntelliCode problems.

**Comment by minestarks** [comment]
@ChrisLebbano  For next steps, please check out this guide which details some troubleshooting steps and reporting instructions for TypeScript language service performance issues.
 https://github.com/microsoft/TypeScript/wiki/Performance#investigating-issues 

Thanks!

**Comment by ChrisLebbano** [comment]
@minestarks  thanks for the response.  I'm not sure these will help because that portion of the wiki seems to revolve around TSC and compiling TypeScript into JS.  The issue I am having is without any compiling or TypeScript itself doing anything really.  This issue is happening just within the VSCode application before any webpack or tsc being run.

Note also at this point, I am running VSCode with no extensions at all and the issue is still occurring, even after a reinstall.

I will continue to try to resolve the issue but this should remain closed

**Comment by minestarks** [comment]
@ChrisLebbano  yeah, sorry the wiki page jumps around a bit between topics, but it still contains sections relevant to editor / language service performance. Those are what you'd want to be looking at (I searched the page for "edit" to find some relevant info)

**Comment by ChrisLebbano** [comment]
Okay, thanks for the heads up.  I'll give it another study shortly.
