### ISSUE TITLE
Java completion items are missing

### ISSUE THREAD

**Issue by jmbockhorst** [MicrosoftDocs/intellicode#164]
I found a bug with Java completion items that are not showing up using intellicode. They do show up after editing the function name, but not when using the "." (See video). I did verify that if I disabled the intellicode extension, it worked properly. 

**Product and Version** [VS/VSCode]: VSCode 1.42.0-insider (Commit: 5dcf2c96b6562b3aa879dbb455de4b58e17cb804)
**OS Version** [macOS/Windows]: Windows_NT x64 10.0.19546
**IntelliCode Extension Version**: 1.2.4
**Target Platform or Language** [e.g. Node.js]: Java

**Steps to Reproduce / Scenario:**

1. Use Spring Boot `JdbcTemplate` (org.springframework.jdbc.core.JdbcTemplate) variable
2. Try find the `update()` functions bring pressing "." after the variable name.

![completion](https://user-images.githubusercontent.com/44308390/73199548-a4da6800-40fa-11ea-884d-6142b8e4e8f7.gif)

**Comment by hexiaokai** [comment]
Thank you for reporting this @jmbockhorst ! This is possibly related to a recent behavior change in the latest release of the Java language server. The change was to only return the top 50 items of all the results returned by the completion engine. The purpose of this change is to improve the responsiveness of IntelliSense but turns out IntelliCode is now ranking among  a partial list which might not have the desired items.

Could you try update the java.completion.maxResults preference. By default, it’s limited to 50 completion results. You can change it to 0 to see the full results list and verify if the issue is mitigated. If this is the case, it would be great if you can open a separate issue in https://github.com/redhat-developer/vscode-java/issues and we will fix it from the Java side.

**Comment by jmbockhorst** [comment]
Thank you. Indeed, it works as intended when the limit is changed to 0. I made a new issue here: https://github.com/redhat-developer/vscode-java/issues/1257

**Comment by Eskibear** [comment]
@jmbockhorst IntelliCode 1.2.6 has been released with the fix.

**Comment by jmbockhorst** [comment]
Verified that the update fixes this.
