### ISSUE TITLE
IntelliCode conflicts with Go to & Peek Features?

### ISSUE THREAD

**Issue by iaso2h** [MicrosoftDocs/intellicode#166]
There is a poped up notification that says IntelliCode python support requires you to use the Microsoft Python Language Server(preview). When I enable it and reload VS Code, I can no longer use the Go to & Peek Definition, Declaration and References function. 

![screenshot_20200205_124417](https://user-images.githubusercontent.com/11383694/73811816-7d2f8200-4815-11ea-9681-0cf458c0e640.png)

I noticed there is a additonal line `"python.jediEnabled": false"` in my setting.json after I take the pop-up's advice. I can connitue to use the Go to & Peek features when I comment out that line, which is my hypothesis that IntelliCode conflicts with Go to & Peek features. I'm scripting Python in VS Code right now and I'm not sure whether it's a personal issue or anything.

**Comment by vivlimmsft** [comment]
The `"python.jediEnabled": false"` setting controls whether you are using the Microsoft Python Language Server. IntelliCode itself has no impact on Go to & Peek.

It looks like a similar issue was reported almost a year ago in the vscode-python repo: https://github.com/microsoft/vscode-python/issues/5033. That issue was fixed in an update to the language server.
I didn't see any more recent reports of this, so I suggest opening a new issue in vscode-python.

**Comment by markw-t** [comment]
Resolving per @vivlimmsft comments above
