### ISSUE TITLE
When python.jediEnabled=false an error occurs unresolved import 'config'

### ISSUE THREAD

**Issue by sergeos** [MicrosoftDocs/intellicode#187]
Hi,
Maybe someone solve a problem, when in a language preferences value
_python.jediEnabled=false_, then there is an error **unresolved import 'config'**?
![изображение](https://user-images.githubusercontent.com/7515761/79810471-d1112800-837b-11ea-90dd-86543ded528d.png)
but, if i'm commented this line, all OK.
![изображение](https://user-images.githubusercontent.com/7515761/79812033-55fe4080-8380-11ea-93e7-689337b4bcf6.png)

**Comment by MikhailArkhipov** [comment]
@sergeos - this looks like `Microsoft` language server issue rather than IntelliCode. IntelliCode does not support Jedi language engine so when you set `jediEnabled` to `false`, you activated `Microsoft Language Server`. You can file a bug for the LS here https://github.com/microsoft/python-language-server. There is also a troubleshooting guide for imports: https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#unresolved-import-warnings

However, have you tried new `Pylance` language server? https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance.

**Comment by ayim** [comment]
Closing this issue since jedi has been deprecated
