### ISSUE TITLE
IntelliCode

### ISSUE THREAD

**Issue by Onet1m3** [MicrosoftDocs/intellicode#202]
Issue Type: <b>Bug</b>

К сожалению, при включении поддержки IntelliCode для Python возникла ошибка. Дополнительные сведения см. в окнах вывода "Python" и "Visual Studio IntelliCode"

Extension version: 1.2.7
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.15GB (3.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by markw-t** [comment]
Sorry you are seeing this issue: "Unfortunately, there was an error when intelliCode support was enabled. For more information, see "Python" and "Visual Studio IntelliCode"

We need a little more information to be able to diagnose correctly. 

If the issue is still appearing for you, can you paste in the content of your VS IntelliCode output pane in the Output panel, which should have diagnostic information when a failure occurs? 

Thanks!

**Comment by markw-t** [comment]
@Onet1m3 - since we haven't heard back from you I'm closing this issue pending more info as described above. If you hit it again, the above info will really help us to figure out what's going on. Thanks for using IntelliCode!

**Comment by Hloredea** [comment]
I have same issue and code don't highlight variables, functions etc, like I can't open import code with Ctrl+LMB
