### ISSUE TITLE
在文档“*.py”中找不到符号，且代码不提示

### ISSUE THREAD

**Issue by zhangxiang1209** [MicrosoftDocs/intellicode#209]
Issue Type: <b>Bug</b>

突然出现的问题

Extension version: 1.2.9
VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (8.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>

**Comment by markw-t** [comment]
For non-Chinese speakers an autotranslation reads The symbol could not be found in the document ".py" and the code does not prompt.

**Comment by luabud** [comment]
@zhangxiang1209 this seems to be a Python extension issue. Would you mind trying out our [new language server ](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) to see if it solves your issue? Otherwise we'd be happy to assist you in [our GitHub repo](https://github.com/microsoft/vscode-python/issues/new?labels=classify%2C+type-bug&template=2_bug_report.md).

**Comment by markw-t** [comment]
Based on @luabud 's comment this seems like it's a Python extension issue. If we are mistaken, please re-open this issue.

**Comment by zhangxiang1209** [comment]
Thank you for your reply. It is confirmed that it is the python extension issue. After I installed **pylance**, the **problem was solved.**
