### ISSUE TITLE
C# interface change to same interface

### ISSUE THREAD

**Issue by Dadsgoosen** [MicrosoftDocs/intellicode#228]
This is merely feedback to intellicode. 

I changed a couple of interfaces to inherit from one interface to another and when checking the changed to interface it suggests to inherit from the same interface. I have attached a screenshot showing the suggestion.

Visual Studio 2019 Enterprise
Windows 10
C# latest version

![intellicode_interface_suggestion](https://user-images.githubusercontent.com/14332502/94041237-4325e700-fdca-11ea-8a2c-28401e4f59d0.png)

**Comment by markw-t** [comment]
Hi @Dadsgoosen - thanks for raising this issue. We are working on tightening our suggestion filters to ensure they don't produce non-compilable code; we're aware of several cases where bad suggestions get through at present in the Visual Studio 2019 16.7 release.  Your case is verified as one of those and will be fixed in an upcoming update to Visual Studio. 

I hope you are finding the IntelliCode suggestions feature useful in other places - please do report any other bad suggestions you see, here or via [Visual Studio "report a problem" ](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019#:~:text=Here%20are%20the%20steps%20to%20report%20a%20problem.,screenshot.%20Follow%20the%20instructions%20on-screen%20to%20sign%20in.)

Again thanks for using IntelliCode!

Regards
Mark
