### ISSUE TITLE
intellicode not working for java

### ISSUE THREAD

**Issue by Anavi18** [MicrosoftDocs/intellicode#249]
**Product and Version** [VS/VSCode]: VSCode
**OS Version** [macOS/Windows]: Windows 10
**IntelliCode Extension Version**: yes
**Target Platform or Language** [e.g. Node.js]:

**Steps to Reproduce / Scenario:**

1.
2.

**Comment by catycaldwell** [comment]
@Anavi18  can you include more information?

**Comment by Anavi18** [comment]
Whenever I type my code, the suggestions do not come as they used to. Even after I have finished typing there's no suggestion.
I have tried reinstalling VSCode as well as the extension pack but nothing helped.

**Comment by Eskibear** [comment]
@Anavi18 Can you provide logs from output channel "VS IntelliCode", e.g. 
![image](https://user-images.githubusercontent.com/2351748/100718788-b5343100-33f6-11eb-902c-f83a090ec79f.png)

Please also check "Language Support for Java" for any error message (if exists).

**Comment by markw-t** [comment]
@Anavi18 since we don't have the output channel log info that @Eskibear requested above, we cannot take any further action on this issue. If you are still seeing this issue and can provide the logs from the output pane "VS IntellICode" as described to help us investigate, please feel free to re-open this issue.
