### ISSUE TITLE
Couldn't download IntelliCode model. Please check your network connectivity or firewall settings.

### ISSUE THREAD

**Issue by Leastrio** [MicrosoftDocs/intellicode#272]
```
Language server is set to Pylance.
Acquiring model
Acquiring model 'intellisense-members-lstm-pylance' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Downloading model.
Starting download of https://cdsmprodstg.blob.core.windows.net/models-prod-output/Output_E61945A9A512ED5E1A3EE3F1A2365B88F8FE_E4E9EADA96734F01970E616FAB2FAC19?sv=2018-03-28&sr=b&sig=mOhOJ%2BTuFJHlb9e%2F13E4LoTh35QWkxJ6WhIfOpFo7RE%3D&se=2021-02-11T07%3A32%3A41Z&sp=r
Download complete.
Could not reach the IntelliCode service. Checking the local model cache.
None of the cached models match.
Couldn't download IntelliCode model. Please check your network connectivity or firewall settings. Error Message: EPERM: operation not permitted, open 'C:\Program Files\Microsoft VS Code\models.json', (Error)
No model v2 available for Python, trying v1.
```

Trying to open a python file gives me this error.  Im on windows 10 and VSCode version 1.53, Intellicode version 1.2.11

**Comment by Leastrio** [comment]
I created a json file in the C:\Program Files\Microsoft VS Code\models.json path and that seemed to fix it.

**Comment by vivlimmsft** [comment]
It's strange that `models.json` was created there, it's usually created within the .vscode folder owned by your user. Could you please check your config.json and see if the setting `vsintellicode.modelDownloadPath` is configured? (and if it is, what it's configured to)

Either way we should print a different error message when download fails due to a local permissions issue, as the current message makes it seem like a network issue.

**Comment by Leastrio** [comment]
Where do I find my config.json?

**Comment by Leastrio** [comment]
Nevermind! Found it. the ```vsintellicode.modelDownloadPath``` is just set to ```""```
