### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by mart-256** [MicrosoftDocs/intellicode#286]
- Issue Type: `Bug`
- Extension Name: `vscodeintellicode`
- Extension Version: `1.2.12`
- OS Version: `Windows_NT x64 10.0.19041`
- VS Code version: `1.55.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by mart-256** [comment]
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 1315,
		"activateCallTime": 4,
		"activateResolvedTime": 34,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "VisualStudioExptTeam.vscodeintellicode",
				"_lower": "visualstudioexptteam.vscodeintellicode"
			},
			"activationEvent": "onLanguage:python"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Error: read ECONNRESET"
		}
	]
}
```

**Comment by shwetha1729** [comment]
Hi @mart-256 - sorry you are hitting this issue. Could you give us more detail on when you're seeing this issue so that we can try to reproduce it? 

From the error message this looks like a connection issue, if you're behind a proxy or firewall that could be the reason for the connection being rejected.

Thanks,
Shwetha

**Comment by DavidObando** [comment]
Hi @mart-256, are you still running into issues getting IntelliCode to work?

**Comment by mart-256** [comment]
yes....my intellicode does not work at all

**Comment by ayim** [comment]
Hi @mart-256 are you still experience issues here?
Feel free to open a new issue if you are, would love to hear from you.
