### ISSUE TITLE
IntelliCodeCppPackage does not load correctly

### ISSUE THREAD

**Issue by dnhuy4869** [MicrosoftDocs/intellicode#318]
**Product and Version** [VS]: Visual Studio Professional 2019
**OS Version** [Windows]: Home Single Langue
**IntelliCode Extension Version**:  Latest

I always get this error. I already tried all way i found in google.
- Delete ComponentModelCache, repair Visual Studio
But that error always come after few times usage. Please fix it
![osqFR](https://user-images.githubusercontent.com/73681373/139788551-c010aca8-fc12-4866-aa56-03ad0a0880a2.png)

**Comment by DavidObando** [comment]
Hey,

Next time you get that same error, can you please share the ActivityLog.xml file that's in the mentioned path with us? You may want to send this via the "report a problem" button in Visual Studio rather than uploading it here.

![image](https://user-images.githubusercontent.com/950290/141844668-e9296bb6-e037-476c-93e4-7a5696e69d63.png)

Thanks!

David.
