### ISSUE TITLE
Unable to read IntelliCode metadata.

### ISSUE THREAD

**Issue by Vincent0706** [MicrosoftDocs/intellicode#320]
When I open vscode, the python LSP report such information:
![image](https://user-images.githubusercontent.com/82581024/140448717-a11a3941-42c2-44d4-bb8b-fb3cd0753bb8.png)
~~~
[Info  - 下午9:15:15] Pylance language server 2021.11.0 (pyright fb86eac6) starting
[Info  - 下午9:15:15] Server root directory: c:\Users\thinkpad\.vscode\extensions\ms-python.vscode-pylance-2021.11.0\dist
[Error - 下午9:15:16] Unable to read IntelliCode metadata. Exception Error: ENOENT: no such file or directory, open 'd:\Visual Studio code\extensions\visualstudioexptteam.vscodeintellicode-1.2.14\cache\E61945A9A512ED5E1A3EE3F1A2365B88F8FE_E4E9EADA96734F01970E616FAB2FAC19', Error code: ENOENT
[Error - 下午9:15:16] Unable to close model zip. Exception Error: ENOENT: no such file or directory, open 'd:\Visual Studio code\extensions\visualstudioexptteam.vscodeintellicode-1.2.14\cache\E61945A9A512ED5E1A3EE3F1A2365B88F8FE_E4E9EADA96734F01970E616FAB2FAC19', Error code: ENOENT
~~~
And the path "d:\Visual Studio code\extensions\visualstudioexptteam.vscodeintellicode-1.2.14\cache" is the old vscode extension path.

**Comment by DavidObando** [comment]
Hi,

Can you check if your file system is writable under `d:\Visual Studio code\extensions\visualstudioexptteam.vscodeintellicode-1.2.14\cache`? If it's read-only, or if the storage drive is full, you may see the error above.

If the issue is related to the path being read-only, you can fix that by setting "vsintellicode.modelDownloadPath" explicitly to a writable directory in settings.json.

**Comment by Vincent0706** [comment]
OK, thanks a lot.
