### ISSUE TITLE
IntelliCode Completions WLC extension very slow - not producing predictions

### ISSUE THREAD

**Issue by ayim** [MicrosoftDocs/intellicode#358]
Was trying to recreate https://github.com/microsoft/vscode/pull/110268/commits/2f7f100e4492dad6fc8d5c237798c09c3e90c740.
WLC initially gave some suggestions in the session, then stopped providing completions.

Language: TypeScript

Version: 1.66.2 (user setup)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22581

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/10951869/166389882-44c61975-1745-47b1-9672-a65888fe9f94.png">

**Comment by ayim** [comment]
WLC output window:
[output.txt](https://github.com/MicrosoftDocs/intellicode/files/8607112/output.txt)

**Comment by ayim** [comment]
Restarted VSCode, reattempted:
[outputattempt2.txt](https://github.com/MicrosoftDocs/intellicode/files/8607703/outputattempt2.txt)

**Comment by vivlimmsft** [comment]
Did you mean to link to another issue in the OP? I just see a commit in the vscode repo.
![image](https://user-images.githubusercontent.com/27872315/166396471-bd14b89a-dfde-43d2-820b-6de244f55282.png)

I've seen this timing-out issue on my own machine occasionally, I'll find some time to look into it.

**Comment by ayim** [comment]
@vivlimmsft I was recreating the codechange in that commit on the VSCode repo for some testing - so that's a link to the 'file" and exact changes I was making

**Comment by ayim** [comment]
Thoughts to self:
Do we have the same crashing issues in Python? JS?
Do we have the same timeout/crashing issue on MacOS?

**Comment by vivlimmsft** [comment]
The reason the requests are timing out is because of an unhandled error somewhere in the code that converts text into token ids. We call a function (`TextToIds`) which lives inside a wasm module, so the issue could be in that module, or could be in our wrapper code calling it incorrectly.

Two errors I've seen (this is not exhaustive, just giving some specific examples):
* RuntimeError: null function or function signature mismatch
* memory access out of bounds (😰)

These errors don't seem recoverable, future requests fail even if I catch the error and prevent the worker thread from terminating.

**Comment by jinu-jang** [comment]
How can I reproduce this bug?
Is there a certain context, or do I just have to use it for a bit?

**Comment by ayim** [comment]
@jinu-jang https://github.com/microsoft/vscode/commit/2f7f100e4492dad6fc8d5c237798c09c3e90c740
^try making the code changes in this commit - should run into the bug

**Comment by ayim** [comment]
Issue has been resolved
