### ISSUE TITLE
intellicode incorrect order on typing

### ISSUE THREAD

**Issue by DevTrong** [MicrosoftDocs/intellicode#36]
**Product and Version**: VSCode
**OS Version**: macOS and Windows
**IntelliCode Extension Version**: 1.1.0
**Target Platform or Language**: TypeScript

**Steps to Reproduce / Scenario:**

1. trigger intellisense
![image](https://user-images.githubusercontent.com/3624351/49787961-50bec980-fd28-11e8-89b6-aa55dd5730d3.png)

2. proceed writing desired method or property
![image](https://user-images.githubusercontent.com/3624351/49788005-73e97900-fd28-11e8-8d8d-5cfacf903ca8.png)

3. press enter -> incorrect method gets selected
![image](https://user-images.githubusercontent.com/3624351/49788061-a1362700-fd28-11e8-87de-748468f0684d.png)

**Expected Behaviour**
.subscribe should be the first on the list.

**Comment by jkeech** [comment]
@DevTrong, are you using VS Code Stable (1.29)? I believe this issue was recently fixed in Insiders, so it should be available in stable as soon as VS Code releases the next Stable build.

Stable (1.29):
![image](https://user-images.githubusercontent.com/746020/49817640-a2b22000-fd25-11e8-9977-9da2117b08d7.png)

Insiders (1.30):
![image](https://user-images.githubusercontent.com/746020/49817747-ec9b0600-fd25-11e8-89e2-8ffe4ad0c2d1.png)

**Comment by DevTrong** [comment]
Tried it with VSCode Stable. Insider fixed it 👍
