### ISSUE TITLE
[VS] Feature Request: Share custom models publicly for Open Source Repos

### ISSUE THREAD

**Issue by warrenbuckley** [MicrosoftDocs/intellicode#39]
**Product and Version** [VS/VSCode]: VS Professional 2017 - 15.9.3
**OS Version** [macOS/Windows]: Windows 10 - Build 
**IntelliCode Extension Version**: 
**Target Platform or Language** [e.g. Node.js]: C#

**Scenario:**

I work for a company Umbraco where our CMS is written C# and is available on GitHub. It would be great for anyone who is working with the Umbraco source code and that includes our wider community who contribute bug fixes etc.

It would be a great out of box experience if we can ship the custom model in the repo so that all users contributing to the code get the Intellicode suggestions

**Comment by jkeech** [comment]
@warrenbuckley, thanks for the suggestion. We are considering other ways of sharing models in the future, including having references to models checked in to the repo (although probably not having the model files themselves checked in since they can change somewhat frequently and would bloat the Git history).

The current sharing functionality can come close to mimicking this behavior. If you generate a sharing link and put it in your Readme in GitHub, then anyone can add that model to their IntelliCode profile. There's no automatic model acquisition, but after it is manually added once, any future updates you publish (via retraining the model as the code changes over time) would get automatically picked up for all users of the model.

**Comment by markw-t** [comment]
@warrenbuckley as @jkeech says, thanks for this suggestion, it's definitely a scenario we're thinking about. If you're willing to chat further about this please drop me a line mwthomas at Microsoft dot com.

**Comment by leoniDEV** [comment]
One (safe and automatic) way to achieve this could be adding a field in the .nuspec file so IntelliCode acquire directly from the nuget package the link to the model

**Comment by catycaldwell** [comment]
normalizing labels

**Comment by ayim** [comment]
Hey folks, we've implemented a deep learning model for C# in VS and C# Dev Kit for VSCode, along with Python in VSCode. This should address the ask here!

https://devblogs.microsoft.com/visualstudio/upgrading-from-intellicode-custom-team-completions-models-to-deep-learning/
