### ISSUE TITLE
IntelliCode in VSCode does not recognize "asp-for" tag error

### ISSUE THREAD

**Issue by bartoligerman497** [MicrosoftDocs/intellicode#398]
**Product and Version** [VS/VSCode]: 1.70 (user setup)
**OS Version** [macOS/Windows]: Windows_NT x 64 10.0.19044
**IntelliCode Extension Version**:  1.2.22
**Target Platform or Language** [e.g. Node.js]: C# ASP .NET 6 Razor

**Steps to Reproduce / Scenario:**

Hello!! I am programming in a .cshtml view and the IntelliCode does not recognize the asp-for tag. 

This is in Visual Studio 2022:
![image](https://user-images.githubusercontent.com/53313625/183262400-3b87cef6-ce99-4692-8ee9-5d06a0895679.png)

But in VSCode:
![image](https://user-images.githubusercontent.com/53313625/183262435-d584038d-fb69-4a97-bceb-bd02853214b9.png)

I know what the error is because it is "Client_Id" with capital letters. But the problem is that the IntelliCode in VSCode does not recognize the error. When I put the mouse over it does not make me the reference to the error as it is Visual Studio. 

This reference works in Visual Studio:
![image](https://user-images.githubusercontent.com/53313625/183263499-26260be3-0f40-4415-8a9d-7cdf4a4ad1a5.png)

![image](https://user-images.githubusercontent.com/53313625/183263518-19cc87af-b004-4a2d-b53b-d73336b0128b.png)

The error does not appear in the "errors" console either.

Thanks and Regards!!

**Comment by markw-t** [comment]
The issue seems to be that the language service you are using for C# (I'm guessing perhaps OmniSharp?) is not providing the Quick Info popups that you see in Visual Studio. This isn't provided by IntelliCode (which only does the AI-assisted development features such as line completions and starred completion list items). 

I think you may want to raise this issue in the repo for the C# language service you are using? (e.g https://github.com/OmniSharp/omnisharp-vscode/issues)
