### ISSUE TITLE
Feature Request: Use Git to determine authorship

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/intellicode#40]
VS2017 15.8.9
Windows 10
Intellicode Extension: 2.0.265.7452
Target language: C#

The IntelliCode FAQ says

> For C# developers, IntelliCode can learn patterns from your code.

"Your code" is pretty loose here. To IntelliCode, "your code" is whatever solution you train on. To me, "your code" is code that _I_ wrote. 

It would be awesome if IntelliCode could look at the Git history to see what code I, individually, wrote and give those lines more weight.

**Comment by markw-t** [comment]
@MisinformedDNA  you're quite right about what IntelliCode considers "your code", with one minor tweak - it's whatever is in the solution**s** you've trained on. 

It's actually deliberate that we learn patterns across the whole of the solution, because we're trying to create a model that leads users to discover and re-use common practices from their codebase (and of course from the broad set of codebases we train our base models on). 

If we restricted learning to your own code, that advantage would be lost, at least for things suggested from custom models. You would only receive suggestions for things you coded yourself.

**Comment by jkeech** [comment]
This is an interesting suggestion. Are you implying that your preferences for which APIs to use should differ from other authors on the same project?

In general, we've been implementing tools that help people provide consistency across a given codebase (EditorConfig is one example). Most projects want to have consistency within their codebases including coding style, API usage patterns, etc, so that it's easy to maintain the codebase over time. Having IntelliCode recommend different suggestions based on who the author is, instead of the code context in which you are operating in, seems like it would be in opposition to that approach.

In other words, IntelliCode is designed to help tell you what it the best/most popular thing do to for the current code you are working on, rather than tell you what you personally prefer. For instance, I might have specific preferences for how things should be done, but I also have to conform to established conventions of each project that I work in, even when they differ from my own preferences. With custom models, IntelliCode adapts to each project and recommends things that are natural for that codebase by using the full corpus of code for the project as the ground truth to provide recommendations. If IntelliCode gave greater weight to recommendations aligned with my personal preferences, then the recommended patterns might diverge from the codebase that I'm working in. It would give me the right thing based on my preferences, but the wrong thing for the project overall.

**Comment by MisinformedDNA** [comment]
I would agree that IntelliCode's EditorConfig generation can help in bring consistency to code in terms of style or usage patterns.

- - -
**Side note:** Though I would argue that even existing code may not be a good standard where

- CMS (or other) source code is being used and makes up a significant portion of the code, even if most of the current development is done is separate files and projects
- Existing source code was not created with any consistency
- Existing source code was created before more recent versions of C# and APIs were introduced. (For instance, expression-bodied methods or Span<T>)

So maybe it's a starting point, but I wouldn't accept it as-is.
- - -

But the AI-assisted IntelliSense seems more like an individual (person) feature. For instance,

1. If the model is for the project/team, then why does each developer need to run it separately instead of it being integrated into the solution?
2. If the model is for the project/team, then why can my model include any other projects I choose?

Finally, I wouldn't expect IntelliSense to be concerned with consistency, but rather with predicting what member I'm going to need next.

**Comment by jkeech** [comment]
@MisinformedDNA, the models can actually be shared so that you have a single model for a solution, and other developers in the team can just add the existing model to their IntelliCode account. Once the model is added, if the model owner retrains the model, all users of the model get the updates automatically. You could see this evolving to have a CI build train and update the model, and all team members or project contributors getting those updates without anyone doing manual training. 

> Finally, I wouldn't expect IntelliSense to be concerned with consistency, but rather with predicting what member I'm going to need next.

If you take that a step further though, the member you need next is dependent on the patterns that are being used in this specific codebase. If IntelliCode recommended a member that you like, but the project doesn't use that pattern for whatever reason, then you would end up having to go back a rewrite it after some PR comments. It's better to recommend the right things for the codebase the first time around to avoid having to rewrite code to follow the best practices for the project.

**Comment by MisinformedDNA** [comment]
The CI idea is pretty cool. But, currently, if I train my model on projects A, B and C and someone else trains their model on projects C, D and E, we will get different IntelliSense for the same project which seems to conflict with your stated goal.

**Comment by markw-t** [comment]
You're quite right @MisinformedDNA , we've enabled a system that doesn't yet _enforce_ consistency; however organizations/groups are free to train and share according to what makes sense for them, and it's possible for a group to agree that they wish to (as a standard for their group) have one person train on A,B,C and then share out their model links to maintain them. We think we may want to go further with this idea as @jkeech says, by creating a CI build/train mechanism of some sort.

**Comment by MisinformedDNA** [comment]
Whatever standard model that a team agrees to, that model is only applied on top of an individual's model and, thus, the patterns of the team and the patterns of everything else on an individual's will be at odds with each other.

It really sounds to me like the individual model isn't nearly as useful as a team model with no individual models at all.

**Comment by markw-t** [comment]
As we enhance and develop IntelliCode, we're interested in working out ways for teams to specify the model(s) that apply to their particular codebase, maintain models automatically (e.g. via their CI process) etc, and be more prescriptive in those cases where a team model is more appropriate as you suggest.  

In the meantime, the current preview supports a variety of patterns of usage without prescribing any of them - it's fairly flexible in the way it supports sharing.  It's perfectly OK for individuals to _not_ have their own personally trained model at all (as you suggest), and just use one that their team has put together and shared (at which point the need to merge individual and team model goes away); equally if a team member or individual developer wants to try out custom model training alone, they can do that too, then decide to share if they find it useful. We'd like to hear how folks get on with different patterns of usage and what they find most useful, to help inform our next steps.

**Comment by catycaldwell** [comment]
normalize labels

**Comment by MisinformedDNA** [comment]
Closed due to lack of interest.
