### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Ks14021999** [MicrosoftDocs/intellicode#403]
- Issue Type: `Performance`
- Extension Name: `vscodeintellicode`
- Extension Version: `1.2.23`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.70.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/krish/AppData/Local/Temp/VisualStudioExptTeam.vscodeintellicode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by markw-t** [comment]
@Ks14021999  please can you attach the file:///c%3A/Users/krish/AppData/Local/Temp/VisualStudioExptTeam.vscodeintellicode-unresponsive.cpuprofile.txt file mentioned above to enable us to route or investigate this issue?

**Comment by raffian** [comment]
FYI - High cpu usage in vscode for me happens when I open folders containing lots of subfolder projects, but looking closely at my issue I discovered it had nothing to do with vsciode extensions - it was my company's real-time virus/malware endpoint security software, consuming 100% cpu and eating up nearly 6Gb of RAM. Just saying

**Comment by ayim** [comment]
@Ks14021999 if you are able to provide logs as requested above, feel free to reopen!
