### ISSUE TITLE
Intellisense is not workin on VS Code please help me.

### ISSUE THREAD

**Issue by Jagdish2022** [MicrosoftDocs/intellicode#404]
Below is the output result for VS Intellicode

Error while activating Python: {"detail":{"name":"Error","message":"Activating extension 'ms-python.python' failed: command 'python.viewOutput' already exists."}}

**Comment by Jagdish2022** [comment]
@leti367

**Comment by markw-t** [comment]
@leti367 this may be a PyLance team issue - please confirm and re-route as needed to their repository

**Comment by leti367** [comment]
@Jagdish2022, based on the logs, the issue happens when we try to activate python extension. Can you share some more details of your environment? Seems I cannot repro this issue on my machine. Here is the info of my environment:
Version: 1.71.0 (system setup)
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:36:10.600Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No

Extension versions:
IntelliCode Verion: 1.2.25,
Python version: 2022.14.0
Pylance version: 2022.9.10

**Comment by Jagdish2022** [comment]
Version: 1.71.0 (user setup)
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:36:10.600Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No

Extension versions:
IntelliCode Verion: 1.2.25,
Python version: 2022.14.0
Pylance version: 2022.9.11

**Comment by leti367** [comment]
Still cannot reproduce with these extensions. Did you install any other extensions? I doubt one of them has duplicate command 'python.viewOutput'. Can you help to uninstall and check?

**Comment by Jagdish2022** [comment]
Hi @leti367,

My Issue got resolved. 

I have uninstalled my python extension along with pylance and it started working now.

Thanks for your support.
