### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Anmol-Agrawal-Codes** [MicrosoftDocs/intellicode#412]
Type: <b>Performance Issue</b>

Few days ago intellisence is working for java but now it is not working and don't know why also I have restarted the application many times but still it is not working.
Please resolve this issue as soon as possible.

Extension version: 1.2.28
VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

**Comment by markw-t** [comment]
This appears to be a Java IntelliSense/Language service problem rather than IntelliCode (AI assisted development). Tagging @Eskibear to confirm and route to the right repository

**Comment by markw-t** [comment]
Hi @Anmol-Agrawal-Codes 

As mentioned I think this is a Java extension issue rather than anything to do with IntelliCode. IntelliCode solely provides the starred suggestions in the completions list for Java, the IntelliSense itself is provided by the Java extension.

I suggest you raise this issue at https://github.com/microsoft/vscode-java-pack/issues
