### ISSUE TITLE
 error highlight in java

### ISSUE THREAD

**Issue by oovaa** [MicrosoftDocs/intellicode#413]
**Product and Version** [VS/VSCode]:
**OS Version** [macOS/Windows]:
**IntelliCode Extension Version**: 
**Target Platform or Language** [e.g. Node.js]:

**Steps to Reproduce / Scenario:**

1. error highlight is not working with  java i have the extinsion package installed and it was working until this morning

**Comment by markw-t** [comment]
I believe this is a core Java extension problem, rather than an IntelliCode issue. I'm tagging @Eskibear to confirm and help route this issue to the right repository

**Comment by oovaa** [comment]
i deleted the extensions and reinstalled them and nothing happen

**Comment by markw-t** [comment]
Hi @oovaa , as mentioned I think this is a Java extension issue rather than anything to do with IntelliCode. IntelliCode solely provides the starred suggestions in the completions list for Java, and does not do any error highlighting.

I suggest you raise this issue at https://github.com/microsoft/vscode-java-pack/issues
