### ISSUE TITLE
Extension tries to download forever

### ISSUE THREAD

**Issue by Quillee** [MicrosoftDocs/intellicode#46]
**Product and Version** [VS/VSCode]: VSCode
**OS Version** [macOS/Windows]: Windows 10
**IntelliCode Extension Version**:  1.1.2
**Target Platform or Language** [e.g. Node.js]: JavaScript and Python

In the output the window, intellicode goes to download the models and seems to do this forever, it doesn't time out or anything. When I click on the link I get an error that the signature is malformed, so I think this is related to Issue #4 
I downloaded the model directly like the other issue says, Is there a way to use the local model before downloading a new one?

![intellicode_info](https://user-images.githubusercontent.com/13733608/50840543-bd7db180-1330-11e9-8ef8-07f89fd164b6.PNG)

**Comment by jkeech** [comment]
@Quillee, are you behind any proxies or strict firewalls that could be blocking the download? If so, could you try enabling the VS Code setting that is described at https://github.com/MicrosoftDocs/intellicode/issues/4#issuecomment-450935237 to see if they fixes your issue?

The way the logic works is that it first contacts the service to see what the latest version of the model is, then it compares that to what you have cached locally. If the service has a newer version, it downloads that one and replaces the older cached version. If it can't talk to the service (offline or behind a proxy/firewall without the right config), then it just uses the latest cached version.

In your case, the extension was able to successfully talk to the model service to get metadata about the latest model, but then when it tried to download the actual model file from blob storage, that is where it is hanging for you.

**Comment by Quillee** [comment]
@jkeech Thank you for responding. I did download the blobs and do as that comment said to do. Yet intellisense doesn't work at all when I am using intellicode.

**Comment by jkeech** [comment]
@Quillee, I was referring to setting the VS Code setting for [enabling Proxy support](https://code.visualstudio.com/updates/v1_30#_network-proxy-support-for-extensions) rather than downloading the file manually. The proxy setting allows many users that are behind a proxy to have IntelliCode download the models automatically and avoids having to manually download the model file. 

If you download the model manually, IntelliCode will still contact the service on extension activation to check for updated models. It is not supposed to hang on the model download, so I'm not sure what's going on there yet, but I'd like to see if you can avoid the issue altogether with the proxy setting.

**Comment by Quillee** [comment]
Ohhhh, I will check when I get back to work tomorrow

**Comment by Quillee** [comment]
I tried setting the proxy setting to override and it still just stalls. I don't have an HTTP_PROXY env variable though. Also, I don't have a proxy server to use. Should that work without setting that variable?

**Comment by jkeech** [comment]
Thanks for trying. If you aren’t in a network environment that uses a proxy, then the setting shouldn’t have any effect.

You said previously that when you clicked the link for the blob storage, it gave you an error saying the signature is malformed. The link should work in the browser as long as it is clicked within 30 minutes of being generated, since that is the expiration on the SAS token that is embedded in the link. If you restart VS Code and open a JS file and then switch to the IntelliCode output window, what happens if you then click the new blob download link? It should prompt you to save the file when opened in a browser. Can you paste the link here (it doesn’t contain any sensitive data since it’s the base model that everyone gets for TS/JS)?

You also mentioned that IntelliSense was not working at all when IntelliCode is installed. Can you confirm that you don’t see any IntelliSense completion lists when typing in JS or Python files? If so, that is most likely an issue with the underlying language service.

**Comment by Quillee** [comment]
Okay I did as you asked. I am also going to include the error I am receiving to this comment when I go to download the blob.
[Here is the link that is generated when I go to a javascript file](https://cdsmprodstg.blob.core.windows.net/models-prod-output/Output_1A3F919CD5B7725108B03C349630A1C82B03_27727BA11B5A4F16B454DA26B9431CE7?sv=2018-03-28&sr=b&sig=j16Wl/flu5Yj+0xAatn1H72vgUaVSxid1ugWijgcHM0=&se=2019-01-09T17:16:58Z&sp=r)
```xml
<Error>
<Code>AuthenticationFailed</Code>
<Message>
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:00932594-501e-0046-0a3a-a8cc8a000000 Time:2019-01-09T16:47:07.5244452Z
</Message>
<AuthenticationErrorDetail>Signature fields not well formed.</AuthenticationErrorDetail>
</Error>
```

The issue where intellisense doesn't work only happens to python. In javascript I still get the list of variables, imported modules, etc.

**Comment by jkeech** [comment]
Ah, it looks like VS Code is doing some url decoding when you click the link, which is breaking the SAS signature. If you copy and paste the link directly in the browser, it should work (until it expires in approximately 5 minutes from this post): https://cdsmprodstg.blob.core.windows.net/models-prod-output/Output_1A3F919CD5B7725108B03C349630A1C82B03_27727BA11B5A4F16B454DA26B9431CE7?sv=2018-03-28&sr=b&sig=j16Wl%2Fflu5Yj%2B0xAatn1H72vgUaVSxid1ugWijgcHM0%3D&se=2019-01-09T17:16:58Z&sp=r

In any case, I think we will need to see a network trace to understand why the call to download the blob is failing/hanging. Could you run Fiddler and capture a trace of the network calls to cdsmprodstg.blob.core.windows.net? If you don't want to attach them to this issue, feel free to email me directly at john.keech@microsoft.com. Let me know if you need any help. Sorry that this issue is affecting you. I'd like to understand the issue so we can fix it. Thanks!

**Comment by Quillee** [comment]
Yeah, the link you gave me worked. Wouldn't VSCode have a trace since it runs in a browser? Can I use that?

**Comment by jkeech** [comment]
That might be possible, but I'm not sure how to do it. VS Code has the dev tools built in, but the network tab doesn't appear to capture network traffic from extensions. Any way you can capture the network traffic should work -- it doesn't have to be Fiddler. I just need to see the HTTP request/response from blob storage to understand why it is hanging since I'm not able to reproduce the issue myself.

**Comment by catycaldwell** [comment]
@Quillee - have you reviewed #4 ? This seems like this may be a similar issue.

**Comment by ayim** [comment]
Hi @[Quillee](https://github.com/Quillee), were you able to get this working?
Let us know if you weren't successful or if you're having trouble by re-opening this issue.

Cheers!
