### ISSUE TITLE
Never Seen IntelliCode Work Once

### ISSUE THREAD

**Issue by DanJ210** [MicrosoftDocs/intellicode#48]
**Product and Version** [VS/VSCode]: 1.30.2
**OS Version** [macOS/Windows]: 1803
**IntelliCode Extension Version**:  1.1.2
**Target Platform or Language** [e.g. Node.js]: C# .Net, JavaScript

**Steps to Reproduce / Scenario:**

1. Install IntelliCode extension

I believe that's all we are supposed to do. I've never seen IntelliCode work once yet, in VS Code. I've created new projects and have edited old ones. No starred suggestion, nothing different than I've already been seeing.

I posted this in a related closed thread but didn't get any reaction so I'm guessing I just have to create a new one. I've disable and even tried reinstalling but still nothing.

**Comment by jkeech** [comment]
The VS Code extension for IntelliCode supports TS/JS, Python, and Java. C#, XAML, and C++ are supported in the Visual Studio extension for IntelliCode. You can see more details about the full set of supported languages and which versions of each editor and IDE they are supported in at https://visualstudio.microsoft.com/services/intellicode/.

Unfortunately, if you are using C# in VS Code, you will not see any IntelliCode recommendations since it's not currently one of the supported IntelliCode languages in VS Code. JavaScript is supposed to work though. If you create a new .js file and type `console.`, do you see the starred suggestions?

![image](https://user-images.githubusercontent.com/746020/50992420-f9994980-14cb-11e9-8297-3e8b0b8441c4.png)

If not, could you paste the output of the VS IntelliCode output window? It should say something like the following:
```
Acquiring model 'intellisense-members' for javascript
Querying IntelliCode service for available models.
Cached model is up to date.
```

If you have IntelliCode installed but don't see any suggestions for .js files, one possibility is that you have another extension installed which is replacing the full completion list (overriding the default language server). In this case, the other extension would be masking the IntelliCode suggestions.

**Comment by DanJ210** [comment]
I saw the stars come up the other day but when I backspaced and retyped the same thing they weren't there, I believe I was in C#. Yes I read about the supported languages.

I did create a new .js filed and typed `console.` and the stars did come up. I went back to C# files to try but I can't seem to get the stars to come up. Not like in Visual Studio.

So maybe I'm just not understanding when and why the AI suggestions would come up. In Visual Studio the extension analyzes your code and models. Maybe that's not happening in VS Code for obvious reasons.

I just thought I'd share my experience anyway just in case I'm doing something wrong or if I can help.
