### ISSUE TITLE
Can't uninstall / disable IntelliCode

### ISSUE THREAD

**Issue by firasrb** [MicrosoftDocs/intellicode#5]
I have the issue described in https://github.com/MicrosoftDocs/intellicode/issues/4

Regular Intellisense is not working, so I am trying to disable or uninstall IntelliCode until a solution is available (and hoping that Intellisense will be enabled). This gives me the message:

> Cannot uninstall extension 'Visual Studio IntelliCode - Preview'. Extension 'Python Extension Pack' depends on this.

Do I have to revert back to VS Code 1.24 in order to get regular Intellisense back, or is there some other way to remove IntelliCode?

**Comment by markw-t** [comment]
@firasrb , sorry that you're hitting issues with regular Python Intellisense.

Installing IntelliCode turns on the new Python language service, and it may be that the problems you are seeing with regular IntelliSense relate to that. For issues with the new Python language service itself, rather than the IntelliCode recommendations, please can you report at [their GitHub Issues Repo](https://github.com/Microsoft/vscode-python/issues/new) - any messages you're seeing in the Python output window in Visual Studio Code when the failure occurs may be helpful.

We are working on a simple way to disable IntelliCode without having to uninstall it (watch for updates), but in the meantime: 

1.	Set 'jediEnabled': true in your VS Code user settings (you'll find its set to false right now) to turn off the new Python Language Service.

2.	Reload the VS Code window (vscode-python will also prompt when jediEnabled changes)

Unfortunately, you'll find that each time VS Code is re-opened for Python work, it will ask you if you wish to re-enable the new language service so IntelliCode can run - say no to these requests. We'll provide a way to disable IntelliCode and prevent these prompts from appearing shortly.


Mark

**Comment by firasrb** [comment]
Thanks for the replay. As I mentioned in the other issue, I found a workaround to get the IntelliCode model.  This means I no longer need to resolve this issue.

It's great to know that you are working on an easier way to disable IntelliCode so that regular Intellisense may be used if need be.

**Comment by vivlimmsft** [comment]
Hi @firasrb, we just released a new version of the extension which adds a setting you can use to turn off VSCode IntelliCode without having to remove the extension (such as, if it was installed as part of the Python Extension Pack).

Just add this to user settings:
`"vsintellicode.python.completionsEnabled": false`

Viv

**Comment by ollyjshaw** [comment]
@vivlimmsft setting works great in combination with jedi. Thanks
