### ISSUE TITLE
stop working/become slow with Python from time to time

### ISSUE THREAD

**Issue by stevencollinscn** [MicrosoftDocs/intellicode#51]
vscode: 1.30.2
intellicode: 1.1.2
os: Windows 10

For some reason, intellcode is not very unstable and always stop working after a while as I'm not getting any suggestions anymore. I tried to reload the window but it doesn't seem to fix the issue. Does the extension require internet connections or something? I wonder if you guys can consider adding an icon in the status bar to inform the users, like [kite](https://help.kite.com/article/69-using-the-vs-code-plugin) or something.

Except that, intellcode doesn't seem to have lots of methods indexed with Python. Some basic `pandas` methods and attributes, like `.value_counts()` and `.columns`, never show up. In addition, intellicode doesn't seem to index the column name in a pandas DataFrame either since I never got any suggestion while using dot notation to select columns.

https://github.com/Microsoft/vscode-python/issues/4063

**Comment by jkeech** [comment]
@stevencollinscn, when the suggestions stop working, do you mean that all intellisense suggestions stop working, or just the starred IntelliCode suggestions are missing? If all intellisense suggestions stop working, that would most likely indicate a problem with the Python language server.

IntelliCode does require an internet connection to download the models, but once they are downloaded, the local cached copy is used. So you need the network connection initially, but afterwards, offline scenarios should work. We will consider better ways to indicate status of the IntelliCode models/extension to users. Thanks for pointing this out!

----

For your second problem where you are missing some pandas methods and attributes, are those members visible in the normal intellisense list, or do they not show up as options at all? Pandas is included in the Python model, so suggestions should be visible as long as those members are also included in the intellisense list.

IntelliCode primarily uses the language server to figure out which members are possible for a given context, and then re-sorts the best suggestions to the top of the list. If the members are not in the standard intellisense list, then they will also not be recommended by IntelliCode. This sounds like it could be due to this underlying Python language server issue: https://github.com/Microsoft/python-language-server/issues/358.

**Comment by stevencollinscn** [comment]
@jkeech Thanks for the detailed explanation. In my case, it seems that Intellisense stopped working as none of the suggestion showed up, started or unstarted. For those pandas methods, they never show up actually. I will comment on the issue you referenced and wish it will improve in the near future. Thanks again!

**Comment by jkeech** [comment]
Thanks for confirming! In addition to the issue regarding pandas intellisense, you might also want to file a separate issue on the python-language-server repo about intellisense/completions stopping altogether after it's been open for a while.

Closing this issue since both of your issues are related to the underlying python language server.
