### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by laissonsilveira** [MicrosoftDocs/intellicode#60]
- Issue Type: `Performance`
- Extension Name: `vscodeintellicode`
- Extension Version: `1.1.3`
- OS Version: `Linux x64 4.15.0-33-generic`
- VSCode version: `1.31.1`

[VisualStudioExptTeam.vscodeintellicode-unresponsive.cpuprofile.txt](https://github.com/MicrosoftDocs/intellicode/files/2910441/VisualStudioExptTeam.vscodeintellicode-unresponsive.cpuprofile.txt)

**Comment by jkeech** [comment]
This is the second report we've seen for this issue. The other was #59. I took a look at the CPU profile; the trace captured the model download during extension activation, which took a couple seconds. It seems like the bulk of the time was spent in npm module loads, so maybe the webpack solution mentioned [here](https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load#code-loading) might help.

Does this happen regularly for you, or only the first time you used IntelliCode for a new language (when the new model would be downloaded and cached)? Did this seem to impact any of your intellisense/typing scenarios, or was it limited to just the initial extension activation?

**Comment by jkeech** [comment]
I haven't been able to reproduce the high CPU warnings, but I can see that we are doing lots of small npm module loads as part of the http request to our service to download models. Based on the recommendations at https://github.com/Microsoft/vscode/wiki/Explain%3A-extension-causes-high-cpu-load, we can try using webpack to reduce the number and size of files that are loaded.

Our next update (1.1.4) will start using webpack to reduce the extension install size. Early results look good. I don't know for sure if this will solve all of the perf problems, but here's some quick stats on the webpack improvement:

* **VSIX size** went from ~4MB to ~540 KB -- **86% reduction**
* **Install size** on disk went from 12.5 MB to 1.35 MB -- **89% reduction**
* **Number of files** on disk went from 2,786 to 29 -- **99% reduction**

This change should also improve install/upgrade time for the extension, especially on Windows due to the huge reduction in number of files.

**Comment by jkeech** [comment]
Version 1.1.4 has been published to the marketplace with these perf improvements. Please update and let us know if you continue to see these high CPU load notifications. Thanks!

**Comment by penfree** [comment]
now 1.1.6, problem still exists on python

**Comment by jkeech** [comment]
@penfree, please open a new issue with your trace attached. Thanks!
