### ISSUE TITLE
Problems with Visual Studio IntelliCode - Preview & Python

### ISSUE THREAD

**Issue by SirTwsted** [MicrosoftDocs/intellicode#74]
I keep getting an annoying error message.
Also,  When installing Python Extensions Pack, for some reason its over-writing my HTML extensions into DJango.
Not to mention a million other errors im getting after allowing a bunch of extensions to be updated.
Now im getting all sorts of problems with tons of extensions in my VSC.
and its driving me up the walls.
I wish VSC had a Discord Sever,  so I can hang out in the discord and also get help from people.
Anyways........  lets start with this problem.
.
Visual Studio Intellicode - Preview v1.1.4  (extension)
-----
This is the VSC version im using:
-----
Version: 1.32.3 (system setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601
.
![Screenshot_49](https://user-images.githubusercontent.com/15247713/54508916-0730dc80-491e-11e9-82e6-c72b93152fb4.png)

**Comment by jkeech** [comment]
@SirTwsted, sorry you are having so many problems with VS Code. The IntelliCode Python support does require the Microsoft Python Language server to function. Is there a reason that you can't switch to that version of the Python language server?

If you can't (or don't want) to use the Microsoft Python Language server, then the easiest thing to do is disable IntelliCode for Python. You can do this in settings by unchecking this checkbox:
![image](https://user-images.githubusercontent.com/746020/54544022-ef784900-495b-11e9-9316-183b04923472.png)

We can update the toast to povide a clearer option for this case, such as "Don't ask again", which could toggle this setting for you.

**Comment by SirTwsted** [comment]
Thank you for understanding my situation  :)
I dont mind using it and have no problems in regards of the force-able choice when I get notified.
The problem I do have is, that even when I do elect to use it, it keeps nagging me that in order for me to use Python it requires me to use the Microsoft Python Language server....lol
Even though I elected to use, as I didnt mind using it  :)
Every single time I touch any file that has to do with Python, this error message pops up.
If I breath too hard in the direct of a Python file within code, the message pops up....LOL
Now im just terrified to even touch a python file in studio code...LOL

**Comment by jkeech** [comment]
@SirTwsted, can you confirm that you have the "python.jediEnabled": "false" setting set? The toast message should only show up if you have jediEnabled set to true.

**Comment by SirTwsted** [comment]
Its turned on for some odd reason, but Ill now turn it off by "unchecking" the box.   :)
.
![Screenshot_51](https://user-images.githubusercontent.com/15247713/54568063-4c035480-49ac-11e9-861d-0ebd8378ef58.png)

**Comment by jkeech** [comment]
After you turn it off, if you reload VS Code and open a python file, you should not see the toast message anymore.

**Comment by SirTwsted** [comment]
*Smiles*  :D  feels so relieved.
the happiest man on this planet today  :D :D  Hahaha  :D :D
Thank you , thank you thank you :D

**Comment by jkeech** [comment]
Glad it's working for you 😄! If you hit any other issues with IntelliCode, please let us know. Closing this issue.

**Comment by r3gor** [comment]
Tenia el mismo problema con Python, cuando salia el aviso, hacia click a la opción de "enable it and reload window" pero esto no hacia absolutamente nada, ya que ni siquiera notaba el "reload" pues el vs code seguía tal cual solo que el aviso ya no estaba pero volvía a aparecer cada vez que abría un fichero de Python en vs code. Tratando de solucionarlo ejecuté el siguiente comando:  

>Extensions: Open Extensions Folder

luego busque la carpeta con el prefijo ms-python.python y al entrar busque la carpeta de languageServer y me di cuenta que no estaba. 
Luego no entiendo como la verdad ya que solo abrí una carpeta (la de el prefijo ms-python.python) lo cual supongo que no debería solucionar nada, pero al cerrar y abrir en vs code un fichero de python nuevamente me volvió a salir el mismo error, pero esta vez fue diferente porque cuando clickee la opción de "enable it and reload window" esta vez SÍ se pudo ver como el vs code se recargaba y también que comenzaba aparecer en la parte inferior: "Downloading Microsoft Python Language Server ..." Cuando terminó la descargar revise la carpeta de prefijo ms-python.python y esta vez SÍ tenia la carpeta de languageServer. 
Ahora ya no me aparece el error, como digo la verdad ni sé como es que exactamente se solucionó el problema, **soy muy novato aún por lo que esta información no es lo más fiable** pero fue lo que me funcionó y solo quería compartirlo.

No estoy seguro pero creo que da el mismo error cuando Language Server está desactualizado, en ese caso se debe buscar la carpeta languageServer (dentro de ms-python.python) y eliminarla, para que luego al abrir vs code nos descargue la ultima version.

**Comment by gewarren** [comment]
@r3gor Since this issue is closed, can you please create a new issue with your problem? Here is the translated text:

I had the same problem with Python, when the warning came out, clicked on the option of "enable it and reload window" but this did not make absolutely anything, since I didn't even notice the "reload" because the vs code was still just like that the warning was no longer there but it was coming back er every time I opened a Python file in vs code. Trying to fix it, I ran the following command:

Extensions: Open Extensions Folder

then look for the folder with the prefix ms-python.python and when you enter look for the languageServer folder and I noticed that it was not.
Then I do not understand as the truth since I only opened a folder (the one of the prefix ms-python.python) which I suppose should not solve anything, but when closing and opening in vs code a python file again I came out the same error, but this time it was different because when you clicked the option of "enable it and reload window" this time YES you could see how the vs code was reloaded and also that it started to appear at the bottom: "Downloading Microsoft Python Language Server ... " When you finished downloading check the folder of prefix ms-python.python and this time YES had the languageServer folder.
Now I no longer get the error, as I tell the truth nor do I know how exactly the problem was solved, I am very new enough still so this information is not the most reliable but it was what worked for me and I just wanted to share it.

I'm not sure but I think it gives the same error when Language Server is outdated, in that case you should look up the languageServer folder (inside ms-python.python) and delete it, so that later when you open vs code we download the latest version.

**Comment by ionecum** [comment]
You ran the command WHERE?

**Comment by markw-t** [comment]
Hey @ionecum - do you have a new issue to report? Not sure what your comment is in relation to!
