### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by meanis** [MicrosoftDocs/intellicode#77]
- Issue Type: `Performance`
- Extension Name: `vscodeintellicode`
- Extension Version: `1.1.4`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\brahm\VisualStudioExptTeam.vscodeintellicode-unresponsive.cpuprofile.txt
[VisualStudioExptTeam.vscodeintellicode-unresponsive.cpuprofile.txt](https://github.com/MicrosoftDocs/intellicode/files/2991597/VisualStudioExptTeam.vscodeintellicode-unresponsive.cpuprofile.txt)
[VisualStudioExptTeam.vscodeintellicode-unresponsive.cpuprofile.txt](https://github.com/MicrosoftDocs/intellicode/files/2991605/VisualStudioExptTeam.vscodeintellicode-unresponsive.cpuprofile.txt)

` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jkeech** [comment]
I took a look at the CPU trace, and VS Code hung for 10 seconds on a file system call when IntelliCode created the output window via `vscode.window.createOutputChannel("VS IntelliCode")`. Internally, it looks like the extension host process creates some rotating logs to store the output channel content, and for some reason the file system call was slow.

Unfortunately, I don't think there is much that the IntelliCode extension can do in this case, since that's the API that VS Code exposes to [create output channels](https://code.visualstudio.com/api/references/vscode-api#window.createOutputChannel).

**Comment by jkeech** [comment]
This issue has been fixed in VS Code.
