### ISSUE TITLE
Typo mistake in Intellisense configuration

### ISSUE THREAD

**Issue by RicaBenhossi** [MicrosoftDocs/intellicode#78]
Issue Type: <b>Bug</b>

There is an option in Vsintellicode > Modify > Editor: Suggest Selection that has a typo mistake: it's written AutomaticallyOverrOde instead of AutomaticallyOverrIde.

![VSCodeTypoMistake](https://user-images.githubusercontent.com/15204313/55178478-3b996980-5164-11e9-9427-331437d3754b.png)

Extension version: 1.1.5
VS Code version: Code - Insiders 1.33.0-insider (b5f5db349f211f5045e7dad6fd1672010d2d00de, 2019-03-28T10:44:04.956Z)
OS version: Linux x64 4.15.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3217U CPU @ 1.80GHz (4 x 1705)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 0|
|Memory (System)|3.68GB (0.10GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by jkeech** [comment]
The value `automaticallyOverrodeDefaultValue` is intended to indicate that IntelliCode has already done this in the past. IntelliCode automatically overrode the default value for you previously. It's not really a user-selectable value on it's own, but it's more of a state keeping mechanism to help troubleshoot why the `editor.suggestSelection` value might have changed.

`enabled` means you are allowing IntelliCode to change `editor.suggestSelection` on your behalf, but it hasn't done anything yet.
`disabled` means you are not allowing IntelliCode to change `editor.suggestSelection.
`automaticallyOverrideDefaultValue` means that you had set it to `enabled` at some point in the past, and IntelliCode acted on that and changed the value of `editor.suggestSelection` for you to a value that works better with IntelliCode.
`choseToUpdateConfiguration` means that you had it set to `enabled` at some point in the past, and IntelliCode prompted you to change the value of `editor.suggestSelection`, and you chose to change it via the prompt.

The last two settings both indicate that `editor.suggestSelection` was changed due to IntelliCode, but they differentiate automatically changing the value from you being prompted and confirming to change the value. There are different scenarios where each one would happen, which can be seen in more detail at https://github.com/MicrosoftDocs/intellicode/issues/53#issuecomment-470332077.

If you have any suggestions for making the descriptions clearer, please let us know.

**Comment by RicaBenhossi** [comment]
Ohh sorry... I didn't notice that this was a kind of "status" feedback and not an option... It makes sense now.

Thank you so much for your explanation. One more time, sorry my misunderstanding,
